### ISSUE TITLE
Crash on boot trying to retrieve player head

### ISSUE THREAD

**Issue by kevv2** [ForkGG/Fork#51]
Value cannot be null. (Parameter 'path3')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2, String path3, String path4)
   at Fork.Logic.Model.Player.HeadFromCache(String uid) in C:\Users\chris\source\repos\Fork-legacy\logic\model\Player.cs:line 168
   at Fork.Logic.Model.Player.RetrieveHead() in C:\Users\chris\source\repos\Fork-legacy\logic\model\Player.cs:line 184
   at Fork.Logic.Model.Player.InitWithName(String name) in C:\Users\chris\source\repos\Fork-legacy\logic\model\Player.cs:line 46
   at Fork.Logic.Manager.PlayerManager.CreatePlayer(String name) in C:\Users\chris\source\repos\Fork-legacy\logic\manager\PlayerManager.cs:line 166
   at Fork.Logic.Manager.PlayerManager.GetPlayer(String name) in C:\Users\chris\source\repos\Fork-legacy\logic\manager\PlayerManager.cs:line 114
   at Fork.Logic.RoleManagement.RoleUpdater.HandleOutputLine(String line) in C:\Users\chris\source\repos\Fork-legacy\logic\RoleManagement\RoleUpdater.cs:line 93
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

The file doesn't exist in the cache but it tries to get it anyway and crashes whenever the UI loads

**Comment by kevv2** [comment]
Tried investigating why I was getting those issues and it seems like every value that gets deserialized can't edit elements without a setter, adding a set to every values got the program working

**Comment by ChristianKernDev** [comment]
Well not the fastest response, but i am not able to reproduce this anymore in this version of Fork. I think this is only an issue in Fork-Legacy, so i will close this issue here
